import React, { createContext, useContext, useState, useEffect } from 'react';

// ─────────────────────────────────────────────────────────
//  TRANSLATIONS  (English & Sinhala)
//  Add new keys here; use t('key') anywhere in the app.
// ─────────────────────────────────────────────────────────
export const translations = {
    en: {
        // ── Top Bar ──
        sellOnHodama: 'Partner with Hodama Deals',
        becomeClient: 'Become a Business Partner',
        trackOrder: 'Help Center',
        customerSupport: 'Customer Support',
        login: 'Login',
        register: 'Register',
        hiUser: (name) => `Hi, ${name}`,

        // ── Main Nav ──
        categories: 'Categories',
        searchPlaceholder: 'Search deals, offers and more…',
        wishlist: 'Wishlist',
        cart: 'Saved',
        account: 'Account',
        loginRegister: 'Login / Register',

        // ── Category Names ──
        electronics: 'Electronics',
        fashion: 'Fashion',
        homeLifestyle: 'Home & Lifestyle',
        groceries: 'Groceries',
        automotive: 'Automotive',
        sportsFitness: 'Sports & Fitness',
        babyKids: 'Baby & Kids',
        computers: 'Computers',
        healthBeauty: 'Health & Beauty',
        dealsOffers: 'Deals & Offers',
        hotDeals: '🔥 Hot Deals',

        // ── Profile Dropdown ──
        dashboard: 'My Profile',
        overview: 'Overview',
        myOrders: 'Favorite Deals',
        clientPanel: 'Business Dashboard',
        logout: 'Logout',

        // ── Mobile Sidebar ──
        quickLinks: 'Quick Links',

        // ── Footer ──
        footerDesc: 'Hodama Deals is a multi-vendor online marketplace that allows users to buy, sell, and discover new and second-hand products easily and securely — all in one place.',
        quickLinksFooter: 'Quick Links',
        home: 'Home',
        allCategories: 'All Categories',
        newArrivals: 'New Arrivals',
        forBuyers: 'For Buyers',
        myAccount: 'My Account',
        orderHistory: 'History',
        returnsRefunds: 'Privacy & Terms',
        howToBuy: 'How to Claim',
        forClients: 'For Businesses',
        clientDashboard: 'Partner Dashboard',
        clientPolicies: 'Partner Policies',
        howToSell: 'How to List',
        supportContact: 'Support & Contact',
        helpCenter: 'Help Center',
        contactUs: 'Contact Us',
        privacyPolicy: 'Privacy Policy',
        termsConditions: 'Terms & Conditions',
        sitemap: 'Sitemap',
        allRightsReserved: 'All Rights Reserved.',
        newsletterTag: '📢 Stay Updated',
        newsletterHeading: 'Get the Best Deals Delivered to Your Inbox',
        subscribe: 'Subscribe',
        emailPlaceholder: 'Enter your email address…',

        // ── Help Center ──
        helpHeroTitle: 'How can we help you?',
        helpHeroSubtitle: 'Search for categories, questions or contact support',
        helpSearchPlaceholder: 'Describe your issue…',
        helpCatBuying: 'Buying on Hodama',
        helpCatSelling: 'Selling on Hodama',
        helpCatPayments: 'Payments & Refunds',
        helpCatShipping: 'Shipping & Delivery',
        helpCatAccount: 'Account & Security',
        helpSectionFAQ: 'Popular Questions',
        helpContactTitle: 'Didn\'t find what you needed?',
        helpContactSubtitle: 'Our support agents are here to help',
        helpChatTitle: 'Live Chat',
        helpChatDesc: 'Chat with us in real-time',
        helpEmailTitle: 'Email Support',
        helpEmailDesc: 'Expect a reply within 24 hours',
        helpPhoneTitle: 'Call Us',
        helpPhoneDesc: 'Mon-Fri, 9am - 6pm',

        // ── FAQ Dummy Data (English) ──
        faqQ1: 'How do I use a deal?',
        faqA1: 'Simply find a deal you like, and show the offer page or code to the merchant at the physical store location.',
        faqQ2: 'Is it free for businesses?',
        faqA2: 'We offer a 6-month free introductory period for all new partners. After that, a flexible monthly subscription applies.',
        faqQ3: 'How can I become a partner?',
        faqA3: 'Click on "Partner with Hodama Deals" in the top bar to register as a business. Once verified, you can start listing deals.',
        faqQ4: 'What payment methods are supported?',
        faqA4: 'Currently we support direct listing. For subscriptions, we accept Credit/Debit cards and local bank transfers.',
        faqQ5: 'How do I report an expired deal?',
        faqA5: 'Use the "Report a Problem" option in the support form or click the report button on the deal details page.',

        // ── Contact Us Page (English) ──
        contactTitle: 'Contact Us',
        contactSubtitle: 'Have questions or feedback? We are here to help you.',
        contactInfoTitle: 'Contact Information',
        contactEmail: 'Email Address',
        contactPhone: 'Phone Number',
        contactAddress: 'Our Office',
        contactHours: 'Working Hours',
        contactHoursWeek: 'Mon–Fri: 9:00 AM – 6:00 PM',
        contactHoursSat: 'Sat: 9:00 AM – 1:00 PM',
        contactFormTitle: 'Send Us a Message',
        contactName: 'Full Name',
        contactSubject: 'Subject',
        contactMessage: 'Message',
        contactBtn: 'Send Message',
        contactSuccess: 'Thank you! We’ll get back to you soon.',
        contactError: 'Please fill in all required fields.',
        contactSubjGeneral: 'General Inquiry',
        contactSubjSupport: 'Technical Support',
        contactSubjClient: 'Business Partnership',
        contactSubjFeedback: 'Feedback/Report',

        // ── Home Page (English) ──
        homeHeroTitle1: 'Mega Electronics Sale',
        homeHeroSub1: 'Up to 50% Off on latest gadgets',
        homeHeroBtn1: 'Shop Now',
        homeHeroTitle2: 'Fashion Deals Week',
        homeHeroSub2: 'Limited Time Offer on all apparel',
        homeHeroBtn2: 'Explore Deals',
        homeHeroTitle3: 'Latest Smartphones',
        homeHeroSub3: 'Best Prices Available in Sri Lanka',
        homeHeroBtn3: 'Buy Now',
        homeFlashTitle: 'Flash Deals',
        homeFlashEnds: 'Ends In:',
        homePopularTitle: 'Popular Products',
        homeCatGridTitle: 'Shop By Category',
        homeWhyTitle: 'Why Choose Hodama Deals?',
        homeWhySecPay: 'Secure Payments',
        homeWhySecPayDesc: '100% safe transactions',
        homeWhyFastDel: 'Fast Delivery',
        homeWhyFastDelDesc: 'Quick island-wide shipping',
        homeWhyVerClient: 'Verified Clients',
        homeWhyVerClientDesc: 'Shop from trusted vendors',
        homeWhyEasyRet: 'Easy Returns',
        homeWhyEasyRetDesc: '7-day return policy',
        homeClientCTATitle: 'Start Selling on Hodama Deals Today',
        homeClientCTASub: 'Join thousands of clients and reach millions of customers.',
        homeClientCTABtn: 'Become a Client',

        // ── Promo Banner ──
        homePromoTitle: 'THE REAL SALE',
        homePromoStatus: 'LIVE NOW',
        homePromoBtn: 'SHOP NOW',

        // ── Home Page Enhancements (English) ──
        homeBestDealsTitle: "Today's Best Deals",
        homeShopByBrandTitle: 'Shop By Brand',
        searchResult: 'Search Results',
        homeNewlyAddedTitle: 'Newly Added',
        homeRecommendedTitle: 'Recommended For You',
        homeTopClientsTitle: 'Top Rated Clients',
        homeUsedDealsTitle: 'Best Used Item Deals',
        homeSellWithUsTitle: 'Want to reach millions? Sell with us!',
        badgeBestDeal: 'BEST DEAL',
        badgeHot: 'HOT',
        badgeLimited: 'LIMITED',
        stockOnly: 'Only',
        stockLeft: 'items left',
        heroSideDeal1: 'Smartphone Deals',
        heroSideDeal2: 'Fashion Sale',

        // ── Categories Page ──
        catBreadcrumbHome: 'Home',
        catBreadcrumbCurrent: 'Categories',
        catHeroTag: 'Explore All Categories',
        catHeroTitle: 'Shop by',
        catHeroHighlight: 'Category',
        catHeroDesc: 'Browse through thousands of new and second-hand items across all categories. Find the best deals from verified clients on Hodama Deals.',
        catStatCategories: 'Categories',
        catStatProducts: 'Products',
        catStatClients: 'Clients',
        catPopularTitle: 'Popular Categories',
        catAllTitle: 'All Categories',
        catAllSub: 'Find what you\'re looking for across our wide range of categories',
        catCardProducts: 'products',
        catCardViewSubs: 'View Subcategories',
        catCardHideSubs: 'Hide Subcategories',
        catCardShopPrefix: 'Shop',
        catDealsTitle: 'Best Deals Across Categories',
        catDealsEnds: 'Ends in',
        catDealsViewAll: 'View All Deals',
        catFilterBannerTitle: 'Can\'t find what you\'re looking for?',
        catFilterBannerDesc: 'Use our advanced filters to search by price range, condition (New/Used), brand, client, and location.',
        catFilterBannerBtn: 'Browse All Products',
        catSortBy: 'Sort By',
        catFilterBtn: 'Apply',
        catFilterPanelTitle: 'Filter Panel',
        catFilterGroupCondition: 'Condition',
        catFilterGroupPrice: 'Price Range',
        catConditionNew: 'New',
        catConditionUsed: 'Used',
        catConditionRefurbished: 'Refurbished',

        // Category Descriptions & Subs
        descElectronics: 'Smartphones, Laptops, Smart TVs, Audio & Gaming',
        descComputers: 'Laptops, Desktops, Monitors, Peripherals & Storage',
        descFashion: "Men's, Women's & Kids Fashion, Shoes & Accessories",
        descHome: 'Furniture, Kitchen Appliances, Decor & Bedding',
        descGroceries: 'Fresh Produce, Rice, Dairy, Snacks & Beverages',
        descHealth: 'Skincare, Makeup, Hair Care & Grooming Essentials',
        descSports: 'Gym Equipment, Sportswear, Cricket, Football & Cycling',
        descBaby: 'Baby Clothing, Diapers, Toys, Strollers & School Supplies',
        descAutomotive: 'Car & Motorcycle Accessories, Electronics & Spare Parts',
        descUsed: 'Quality Pre-Owned Phones, Laptops, Vehicles & More',

        subSmartphones: 'Smartphones',
        subLaptops: 'Laptops & Computers',
        subTVs: 'Smart TVs & Audio',
        subGaming: 'Gaming Consoles',
        subCameras: 'Cameras & Lenses',
        subAudio: 'Headphones & Earbuds',
        subDesktops: 'Desktop Computers',
        subMonitors: 'Monitors',
        subPeripherals: 'Keyboards & Mouse',
        subStorage: 'Hard Drives & SSD',
        subPrinters: 'Printers & Scanners',

        // ── Product Details ──
        pdCondition: 'Condition',
        pdStockLeft: 'Only {count} items left',
        pdDeliveryEst: 'Estimated Delivery',
        pdDeliveryTo: 'Delivering to',
        pdReturnPolicy: 'Return Policy',
        pdAddToCart: 'Add to Cart',
        pdBuyNow: 'Buy Now',
        pdHighlights: 'Product Highlights',
        pdSpecs: 'Specifications',
        pdReviews: 'Reviews',
        pdDescription: 'Description',
        pdClientInfo: 'Client Information',
        pdClientRating: 'Rating',
        pdClientProducts: 'Products',
        pdClientResponse: 'Response Time',
        pdContactClient: 'Contact Client',
        pdVisitStore: 'Visit Store',
        pdRecommended: 'Recommended For You',

        // ── Buyer Dashboard ──
        dashWelcome: (name) => `Welcome back, ${name} 👋`,
        dashSubtitle: 'Manage your orders and deals here.',
        dashTotalOrders: 'Total Orders',
        dashPendingOrders: 'Pending Orders',
        dashOrdersDelivery: 'In Delivery',
        dashWishlistCount: 'Wishlist Items',
        dashRecentOrders: 'Recent Orders',
        dashOrderID: 'Order ID',
        dashPrice: 'Price',
        dashStatus: 'Status',
        dashAction: 'Action',
        dashView: 'View',
        dashTrackingTitle: 'Order Tracking',
        dashTrackingOrderPlaced: 'Order Placed',
        dashTrackingProcessing: 'Processing',
        dashTrackingShipped: 'Shipped',
        dashTrackingOutForDelivery: 'Out for Delivery',
        dashTrackingDelivered: 'Delivered',
        dashMyWishlist: 'My Wishlist',
        dashRecommendedDeals: 'Recommended Deals',
        dashRecentlyViewed: 'Recently Viewed',
        dashProfileManagement: 'Profile Management',
        dashName: 'Name',
        dashEmail: 'Email',
        dashPhone: 'Phone Number',
        dashAddress: 'Delivery Address',
        dashUpdateProfile: 'Update Profile',
        dashChangePassword: 'Change Password',
        dashAddressManagement: 'Address Management',
        dashAddNewAddress: 'Add New Address',
        dashDefaultAddress: 'Default Address',
        dashNeedHelp: 'Need help?',
        dashContactSupport: 'Contact Support',
        dashViewFAQs: 'View FAQs',
    },
    si: {
        // ── Top Bar ──
        sellOnHodama: 'Hodama Deals සමඟ හවුල්වන්න',
        becomeClient: 'ව්‍යාපාරික හවුල්කරුවෙකු වන්න',
        trackOrder: 'උදව් මධ්‍යස්ථානය',
        customerSupport: 'පාරිභෝගික සේවය',
        login: 'පිවිසෙන්න',
        register: 'ලියාපදිංචි වන්න',
        hiUser: (name) => `ආයුබෝවන්, ${name}`,

        // ── Main Nav ──
        categories: 'කාණ්ඩ',
        searchPlaceholder: 'ඩීල්, දීමනා සොයන්න…',
        wishlist: 'ප්‍රියතා ලැයිස්තුව',
        cart: 'සුරැකි',
        account: 'ගිණුම',
        loginRegister: 'පිවිසෙන්න / ලියාපදිංචිය',

        // ── Category Names ──
        electronics: 'ඉලෙක්ට්‍රොනික්',
        fashion: 'ෆැෂන්',
        homeLifestyle: 'නිවස සහ ජීවන රටාව',
        groceries: 'ගෘහ සේවා',
        automotive: 'වාහන',
        sportsFitness: 'ක්‍රීඩා සහ යෝගිකාව',
        babyKids: 'ළදරු සහ ළමා',
        computers: 'පරිගණක',
        healthBeauty: 'සෞඛ්‍යය සහ අලංකාරය',
        dealsOffers: 'ඩීල් සහ ඉදිරිය',
        hotDeals: '🔥 රස්සා ඩීල්',

        // ── Profile Dropdown ──
        dashboard: 'මගේ පැතිකඩ',
        overview: 'සාරාංශය',
        myOrders: 'මගේ ඇණවුම්',
        clientPanel: 'විකිණිකරු පැනලය',
        logout: 'පිටවෙන්න',

        // ── Mobile Sidebar ──
        quickLinks: 'ඉක්මන් සබැඳි',

        // ── Footer ──
        footerDesc: 'Hodama Deals යනු බහු-අලෙවිකරු මාර්ගගත වෙළඳ අඩවියකි. එය ඔබට නව සහ දෙවනි අත් භාණ්ඩ ලෙහෙසියෙන් සහ ආරක්ෂිතව මිලදී ගැනීමට, විකිණීමට සහ සොයා ගැනීමට ඉඩ සලසයි.',
        quickLinksFooter: 'ඉක්මන් සබැඳි',
        home: 'මුල් පිටුව',
        allCategories: 'සියලු කාණ්ඩ',
        newArrivals: 'නව නිෂ්පාදන',
        forBuyers: 'ගැනුම්කරුවන් සඳහා',
        myAccount: 'මගේ ගිණුම',
        orderHistory: 'ඉතිහාසය',
        returnsRefunds: 'ප්‍රතිපත්ති',
        howToBuy: 'භාවිතා කරන්නේ කෙසේද',
        forClients: 'ව්‍යාපාරිකයන් සඳහා',
        clientDashboard: 'හවුල්කරු පැනලය',
        clientPolicies: 'හවුල්කරු ප්‍රතිපත්ති',
        howToSell: 'ලැයිස්තුගත කරන්නේ කෙසේද',
        supportContact: 'සහාය සහ සම්බන්ධතා',
        helpCenter: 'උදව් මධ්‍යස්ථානය',
        contactUs: 'අප හා සම්බන්ධ වන්න',
        privacyPolicy: 'රහස්‍යතා ප්‍රතිපත්තිය',
        termsConditions: 'නියම සහ කොන්දේසි',
        sitemap: 'අඩවි සිතියම',
        allRightsReserved: 'සියලු හිමිකම් ඇවිරිණි.',
        newsletterTag: '📢 යාවත්කාලීන රැඳෙන්න',
        newsletterHeading: 'හොඳම ඩීල් ඔබේ ඊමේල් වෙත ලබා ගන්න',
        subscribe: 'දායකවන්න',
        emailPlaceholder: 'ඔබේ ඊමේල් ලිපිනය ඇතුළත් කරන්න…',

        // ── Help Center ──
        helpHeroTitle: 'අපට ඔබට උදව් කළ හැකි කෙසේද?',
        helpHeroSubtitle: 'ප්‍රවර්ග, ප්‍රශ්න සොයන්න හෝ සහාය අමතන්න',
        helpSearchPlaceholder: 'ඔබේ ප්‍රශ්නය විස්තර කරන්න…',
        helpCatBuying: 'හෝදම හි මිලදී ගැනීම්',
        helpCatSelling: 'හෝදම හි විකිණීම්',
        helpCatPayments: 'ගෙවීම් සහ ආපසු ගෙවීම්',
        helpCatShipping: 'නැව්ගත කිරීම සහ බෙදා හැරීම',
        helpCatAccount: 'ගිණුම සහ ආරක්ෂාව',
        helpSectionFAQ: 'ජනප්‍රිය ප්‍රශ්න',
        helpContactTitle: 'ඔබ සොයන දේ හමු නොවූයේද?',
        helpContactSubtitle: 'අපගේ සහාය නියෝජිතයින් ඔබට උදව් කිරීමට සූදානම්',
        helpChatTitle: 'සජීවී චැට්',
        helpChatDesc: 'තත්‍ය කාලීනව අප සමඟ කතා කරන්න',
        helpEmailTitle: 'විද්‍යුත් තැපැල් සහාය',
        helpEmailDesc: 'පැය 24ක් ඇතුළත පිළිතුරක් බලාපොරොත්තු වන්න',
        helpPhoneTitle: 'අප අමතන්න',
        helpPhoneDesc: 'සඳුදා-සිකුරාදා, පෙ.ව. 9 - ප.ව. 6',

        // ── FAQ Dummy Data (Sinhala) ──
        faqQ1: 'මගේ ඇණවුම හඹා යන්නේ කෙසේද?',
        faqA1: 'Header හෝ Footer හි ඇති "Track Order" ලින්ක් එක ක්ලික් කර ඔබගේ ඇණවුම් අංකය සහ ඊමේල් ලිපිනය ඇතුළත් කිරීමෙන් ඇණවුම හඹා යා හැකිය.',
        faqQ2: 'භාණ්ඩ ආපසු ලබාදීමේ ප්‍රතිපත්තිය කුමක්ද?',
        faqA2: 'බොහෝ භාණ්ඩ සඳහා දින 7ක ආපසු ලබාදීමේ කාලයක් අපි ලබා දෙන්නෙමු. භාණ්ඩය එහි මුල් ඇසුරුම සහ ටැග් සමඟ තිබිය යුතුය.',
        faqQ3: 'විකිණිකරුවෙකු වන්නේ කෙසේද?',
        faqA3: 'ඉහළ ඇති "හෝදම Deals හි විකිණීම" ලින්ක් එක ක්ලික් කර ලියාපදිංචි වන්න. ඔබගේ සාප්පුව තහවුරු වූ පසු භාණ්ඩ ඇතුළත් කළ හැකිය.',
        faqQ4: 'ගෙවීම් ක්‍රම මොනවාද?',
        faqA4: 'අපි ක්‍රෙඩිට්/ඩෙබිට් කාඩ්පත්, KOKO, Mintpay සහ බැංකු හුවමාරු පිළිගන්නෙමු. තෝරාගත් ප්‍රදේශ සඳහා Cash on Delivery ද පවතී.',
        faqQ5: 'බෙදාහරින කාලය කොපමණද?',
        faqA5: 'සාමාන්‍යයෙන් කොළඹ සහ තදාසන්න ප්‍රදේශවලට වැඩ කරන දින 2-5ක්ද, පිට පළාත්වලට වැඩ කරන දින 3-7ක්ද ගත වේ.',

        // ── Contact Us Page (Sinhala) ──
        contactTitle: 'අප අමතන්න',
        contactSubtitle: 'ඔබට ප්‍රශ්න හෝ ප්‍රතිපෝෂණ තිබේද? අපි ඔබට උදව් කිරීමට සූදානම්.',
        contactInfoTitle: 'සම්බන්ධතා තොරතුරු',
        contactEmail: 'ඊමේල් ලිපිනය',
        contactPhone: 'දුරකථන අංකය',
        contactAddress: 'අපගේ කාර්යාලය',
        contactHours: 'වැඩ කරන වේලාවන්',
        contactHoursWeek: 'සඳුදා-සිකුරාදා: පෙ.ව. 9:00 - ප.ව. 6:00',
        contactHoursSat: 'සෙනසුරාදා: පෙ.ව. 9:00 - ප.ව. 1:00',
        contactFormTitle: 'අපට පණිවිඩයක් එවන්න',
        contactName: 'සම්පූර්ණ නම',
        contactSubject: 'විෂය',
        contactMessage: 'පණිවිඩය',
        contactBtn: 'පණිවිඩය යවන්න',
        contactSuccess: 'ස්තූතියි! අපි ඉක්මනින් ඔබව සම්බන්ධ කර ගන්නෙමු.',
        contactError: 'කරුණාකර අවශ්‍ය සියලුම තොරතුරු ඇතුළත් කරන්න.',
        contactSubjGeneral: 'සාමාන්‍ය විමසීම්',
        contactSubjSupport: 'තාක්ෂණික සහාය',
        contactSubjClient: 'ව්‍යාපාරික හවුල්කාරිත්වය',
        contactSubjFeedback: 'ප්‍රතිපෝෂණ/වාර්තා',

        // ── Home Page (Sinhala) ──
        homeHeroTitle1: 'මහා ඉලෙක්ට්‍රොනික විකිණීම',
        homeHeroSub1: 'නවතම ගැජට් සඳහා 50% දක්වා වට්ටම්',
        homeHeroBtn1: 'දැන් මිලදී ගන්න',
        homeHeroTitle2: 'විලාසිතා සතියේ දීමනා',
        homeHeroSub2: 'සියලුම ඇඟලුම් සඳහා සීමිත කාලීන දීමනා',
        homeHeroBtn2: 'දීමනා පරීක්ෂා කරන්න',
        homeHeroTitle3: 'නවතම ස්මාර්ට් ෆෝන්',
        homeHeroSub3: 'ශ්‍රී ලංකාවේ හොඳම මිල ගණන්',
        homeHeroBtn3: 'දැන්ම ගන්න',
        homeFlashTitle: 'ක්ෂණික දීමනා',
        searchResult: 'සෙවුම් ප්‍රතිඵල',
        homeFlashEnds: 'අවසන් වීමට:',
        homePopularTitle: 'ජනප්‍රිය නිෂ්පාදන',
        homeCatGridTitle: 'ප්‍රවර්ග අනුව මිලදී ගන්න',
        homeWhyTitle: 'ඇයි හෝදම Deals තෝරාගත යුත්තේ?',
        homeWhySecPay: 'ආරක්ෂිත ගෙවීම්',
        homeWhySecPayDesc: '100% ආරක්ෂිත ගනුදෙනු',
        homeWhyFastDel: 'වේගවත් බෙදාහැරීම',
        homeWhyFastDelDesc: 'දිවයින පුරා ඉක්මන් බෙදාහැරීම',
        homeWhyVerClient: 'තහවුරු කළ විකුණුම්කරුවන්',
        homeWhyVerClientDesc: 'විශ්වාසදායක වෙළඳුන්ගෙන් මිලදී ගන්න',
        homeWhyEasyRet: 'පහසු ආපසු ලබාදීම',
        homeWhyEasyRetDesc: 'දින 7ක ආපසු ලබාදීමේ ප්‍රතිපත්තිය',
        homeClientCTATitle: 'අදම හෝදම Deals හි විකිණීම ආරම්භ කරන්න',
        homeClientCTASub: 'දහස් ගණන් විකුණුම්කරුවන් සමඟ එකතු වී පාරිභෝගිකයින් වෙත ළඟා වන්න.',
        homeClientCTABtn: 'විකුණුම්කරුවෙකු වන්න',

        // ── Promo Banner ──
        homePromoTitle: 'නියම සේල් එක (THE REAL SALE)',
        homePromoStatus: 'දැන් ක්‍රියාත්මකයි (LIVE NOW)',
        homePromoBtn: 'දැන්ම ගන්න (SHOP NOW)',

        // ── Home Page Enhancements (Sinhala) ──
        homeBestDealsTitle: 'අද දවසේ හොඳම දීමනා',
        homeShopByBrandTitle: 'වෙළඳ නාම අනුව මිලදී ගන්න',
        homeNewlyAddedTitle: 'අලුතින් එක් කළ නිෂ්පාදන',
        homeRecommendedTitle: 'ඔබ වෙනුවෙන්ම තෝරාගත් නිෂ්පාදන',
        homeTopClientsTitle: 'ප්‍රමුඛතම විකුණුම්කරුවන්',
        homeUsedDealsTitle: 'හොඳම පාවිච්චි කළ නිෂ්පාදන දීමනා',
        homeSellWithUsTitle: 'මිලියන ගණනක් අතරට යන්න අවශ්‍යද? අප සමඟ විකුණන්න!',
        badgeBestDeal: 'හොඳම දීමනාව',
        badgeHot: 'හොට්',
        badgeLimited: 'සීමිතයි',
        stockOnly: 'ඉතිරිව ඇත්තේ',
        stockLeft: 'පමණි',
        heroSideDeal1: 'ස්මාර්ට් ෆෝන් දීමනා',
        heroSideDeal2: 'විලාසිතා විකිණීම',

        // ── Categories Page ──
        catBreadcrumbHome: 'මුල් පිටුව',
        catBreadcrumbCurrent: 'කාණ්ඩ',
        catHeroTag: 'සියලුම කාණ්ඩ ගවේෂණය කරන්න',
        catHeroTitle: 'මහේජ කාණ්ඩ අනුව',
        catHeroHighlight: 'මිලදී ගන්න',
        catHeroDesc: 'සියලුම කාණ්ඩ යටතේ දහස් ගණන් නව සහ දෙවන අත් භාණ්ඩ පරීක්ෂා කරන්න. හෝදම Deals හි තහවුරු කළ විකුණුම්කරුවන්ගෙන් හොඳම දීමනා සොයා ගන්න.',
        catStatCategories: 'කාණ්ඩ',
        catStatProducts: 'නිෂ්පාදන',
        catStatClients: 'විකුණුම්කරුවන්',
        catPopularTitle: 'ජනප්‍රිය කාණ්ඩ',
        catAllTitle: 'සියලුම කාණ්ඩ',
        catAllSub: 'අපගේ පුළුල් පරාසයක කාණ්ඩ හරහා ඔබ සොයන දේ සොයා ගන්න',
        catCardProducts: 'නිෂ්පාදන',
        catCardViewSubs: 'අනු කාණ්ඩ බලන්න',
        catCardHideSubs: 'අනු කාණ්ඩ සඟවන්න',
        catCardShopPrefix: '',
        catDealsTitle: 'කාණ්ඩ හරහා හොඳම දීමනා',
        catDealsEnds: 'අවසන් වීමට',
        catDealsViewAll: 'සියලුම දීමනා බලන්න',
        catFilterBannerTitle: 'ඔබ සොයන දේ හමු නොවූයේද?',
        catFilterBannerDesc: 'මිල පරාසය, තත්ත්වය (නව/පාවිච්චි කළ), සන්නාමය, විකුණුම්කරු සහ ස්ථානය අනුව සෙවීමට අපගේ උසස් පෙරහන් භාවිතා කරන්න.',
        catFilterBannerBtn: 'සියලුම නිෂ්පාදන බලන්න',
        catSortBy: 'මඟින් පෙළගස්වන්න',
        catFilterBtn: 'භාවිතා කරන්න',
        catFilterPanelTitle: 'පෙරහන් පුවරුව',
        catFilterGroupCondition: 'තත්ත්වය',
        catFilterGroupPrice: 'මිල පරාසය',
        catConditionNew: 'නව',
        catConditionUsed: 'පාවිච්චි කළ',
        catConditionRefurbished: 'ප්‍රතිසංස්කරණය කළ',

        // Category Descriptions & Subs (Sinhala)
        descElectronics: 'ස්මාර්ට් ෆෝන්, ලැප්ටොප්, ස්මාර්ට් ටීවී, ශ්‍රව්‍ය සහ ක්‍රීඩා',
        descComputers: 'ලැප්ටොප්, ඩෙස්ක්ටොප්, මොනිටර, සහ දත්ත ගබඩා',
        descFashion: 'පිරිමි, කාන්තා සහ ළමා විලාසිතා, පාවහන් සහ උපාංග',
        descHome: 'ගෘහ භාණ්ඩ, මුළුතැන්ගෙයි උපකරණ, සැරසිලි සහ ඇඳ ඇතිරිලි',
        descGroceries: 'නැවුම් නිෂ්පාදන, සහල්, කිරි නිෂ්පාදන, ස්නැක්ස් සහ බීම වර්ග',
        descHealth: 'සම රැකවරණය, මේකප්, කොණ්ඩා රැකවරණය සහ සනීපාරක්ෂක ද්රව්ය',
        descSports: 'ව්‍යායාම උපකරණ, ක්‍රීඩා ඇඳුම්, ක්‍රිකට්, පාපන්දු සහ පාපැදි',
        descBaby: 'ළදරු ඇඳුම්, ඩයපර්ස්, සෙල්ලම් බඩු, ස්ට්‍රෝලර් සහ පාසල් උපකරණ',
        descAutomotive: 'මෝටර් රථ සහ යතුරුපැදි උපාංග, ඉලෙක්ට්‍රොනික සහ අමතර කොටස්',
        descUsed: 'උසස් තත්ත්වයේ පාවිච්චි කළ දුරකථන, ලැප්ටොප්, වාහන සහ තවත් දේ',

        subSmartphones: 'ස්මාර්ට් ෆෝන්',
        subLaptops: 'ලැප්ටොප් සහ පරිගණක',
        subTVs: 'ස්මාර්ට් ටීවී සහ ශ්‍රව්‍ය උපකරණ',
        subGaming: 'ක්‍රීඩා කොන්සෝල (Gaming Consoles)',
        subCameras: 'කැමරා සහ කාච',
        subAudio: 'හෙඩ්ෆෝන් සහ ඉයර්බඩ්ස්',
        subDesktops: 'ඩෙස්ක්ටොප් පරිගණක',
        subMonitors: 'මොනිටර',
        subPeripherals: 'යතුරුපුවරු සහ මවුස්',
        subStorage: 'හාඩ් ඩ්‍රයිව් සහ SSD',
        subPrinters: 'මුද්‍රණ යන්ත්‍ර සහ ස්කෑනර්',

        // ── Product Details (Sinhala) ──
        pdCondition: 'තත්ත්වය',
        pdStockLeft: 'භාණ්ඩ {count} ක් පමණක් ඉතිරිව ඇත',
        pdDeliveryEst: 'බෙදා හරින දිනය',
        pdDeliveryTo: 'බෙදාහරින ප්‍රදේශය',
        pdReturnPolicy: 'ආපසු ලබාදීමේ ප්‍රතිපත්තිය',
        pdAddToCart: 'කරත්තයට එක් කරන්න',
        pdBuyNow: 'දැන් මිලදී ගන්න',
        pdHighlights: 'නිෂ්පාදන විශේෂාංග',
        pdSpecs: 'පිරිවිතර',
        pdReviews: 'සමාලෝචන',
        pdDescription: 'විස්තරය',
        pdClientInfo: 'විකුණුම්කරුගේ තොරතුරු',
        pdClientRating: 'ශ්‍රේණිගත කිරීම',
        pdClientProducts: 'නිෂ්පාදන',
        pdClientResponse: 'ප්‍රතිචාර දැක්වීමේ මට්ටම',
        pdVisitStore: 'වෙළඳසැලට පිවිසෙන්න',
        pdContactClient: 'විකුණුම්කරු සම්බන්ධ කරගන්න',
        pdRecommended: 'ඔබ වෙනුවෙන්ම තෝරාගත්',

        // ── Buyer Dashboard ──
        dashWelcome: (name) => `නැවත සාදරයෙන් පිළිගනිමු, ${name} 👋`,
        dashSubtitle: 'ඔබේ ඇණවුම් සහ දීමනා මෙතැනින් කළමනාකරණය කරන්න.',
        dashTotalOrders: 'මුළු ඇණවුම්',
        dashPendingOrders: 'ප්‍රමාද වූ ඇණවුම්',
        dashOrdersDelivery: 'බෙදාහැරීමේ පවතින',
        dashWishlistCount: 'ප්‍රියතා ලැයිස්තු භාණ්ඩ',
        dashRecentOrders: 'මෑතකාලීන ඇණවුම්',
        dashOrderID: 'ඇණවුම් අංකය',
        dashPrice: 'මිල',
        dashStatus: 'තත්ත්වය',
        dashAction: 'ක්‍රියාව',
        dashView: 'බලන්න',
        dashTrackingTitle: 'ඇණවුම් හඹා යාම',
        dashTrackingOrderPlaced: 'ඇණවුම ලබා දී ඇත',
        dashTrackingProcessing: 'සකසමින් පවතිී',
        dashTrackingShipped: 'නැව්ගත කර ඇත',
        dashTrackingOutForDelivery: 'බෙදාහැරීමට පිටත් කර ඇත',
        dashTrackingDelivered: 'බෙදා හැර ඇත',
        dashMyWishlist: 'මගේ ප්‍රියතා ලැයිස්තුව',
        dashRecommendedDeals: 'නිර්දේශිත දීමනා',
        dashRecentlyViewed: 'මෑතකදී නැරඹූ',
        dashProfileManagement: 'පැතිකඩ කළමනාකරණය',
        dashName: 'නම',
        dashEmail: 'ඊමේල්',
        dashPhone: 'දුරකථන අංකය',
        dashAddress: 'බෙදාහැරීමේ ලිපිනය',
        dashUpdateProfile: 'පැතිකඩ යාවත්කාලීන කරන්න',
        dashChangePassword: 'මුරපදය වෙනස් කරන්න',
        dashAddressManagement: 'ලිපින කළමනාකරණය',
        dashAddNewAddress: 'අලුත් ලිපිනයක් එක් කරන්න',
        dashDefaultAddress: 'පෙරනිමි ලිපිනය',
        dashNeedHelp: 'සහාය අවශ්‍යද?',
        dashContactSupport: 'සහාය කණ්ඩායම අමතන්න',
        dashViewFAQs: 'නිතර අසන ප්‍රශ්න බලන්න',
    },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
    // Try to restore from localStorage, fall back to 'en'
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('hd_language') || 'en';
    });

    // Persist selection
    useEffect(() => {
        localStorage.setItem('hd_language', language);
        // Also set html lang attribute for accessibility / SEO
        document.documentElement.lang = language === 'si' ? 'si' : 'en';
    }, [language]);

    // Translate helper — supports functions (for dynamic strings)
    const t = (key, ...args) => {
        const val = translations[language]?.[key] ?? translations['en']?.[key] ?? key;
        return typeof val === 'function' ? val(...args) : val;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

// ─────────────────────────────────────────────────────────
//  HOOK
// ─────────────────────────────────────────────────────────
export const useLanguage = () => {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used inside <LanguageProvider>');
    return ctx;
};

export default LanguageContext;
